Add French Elections Memos reuse in homepage
ambanum/OpenTermsArchive.org pull request #126
Opened 2022-05-09 08:28 UTC by clementbiron

2022-06-12 20:51 UTC, MattiSG requested changes
Why are the illustrations not full width? 🙂 This looks surprisingly small compared to the other ones.

<img width="1268" alt="Screen Shot 2022-06-12 at 22 50 31" src="https://user-images.githubusercontent.com/222463/173253098-63ab140f-3ceb-49bc-ac02-c6b82017c33e.png">

2022-06-12 20:51 UTC, MattiSG commented on src/translations/fr/homepage.json
> +  "reuses.memos-elections-fr.subtitle": "Suivi du comportement des plateformes sur des périodes électorales.",
All phrasings are in the active phrasing and the present tense.
```suggestion
  "reuses.memos-elections-fr.subtitle": "Suivi du comportement des plateformes sur des périodes électorales.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Suivi du comportement des plateformes sur des périodes électorales.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Suivi du comportement des plateformes sur des périodes électorales.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Suit le comportement des plateformes en période électorale.",
```

2022-06-12 20:51 UTC, MattiSG commented on src/translations/en/homepage.json
> +  "reuses.memos-elections-fr.subtitle": "Tracking platforms behaviour over electoral periods.",
All phrasings are in the active tense.
```suggestion
  "reuses.memos-elections-fr.subtitle": "Tracks major platforms behaviour over the French 2022 elections.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Tracking platforms behaviour over electoral periods.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Tracking platforms behaviour over electoral periods.",
```
```suggestion
  "reuses.memos-elections-fr.subtitle": "Tracking platforms behaviour over electoral periods.",
```

2022-06-12 20:51 UTC, MattiSG commented on src/translations/en/homepage.json
> +  "reuses.memos-elections-fr.subtitle": "Tracking platforms behaviour over electoral periods.",
All phrasings are in the active tense.
```suggestion
  "reuses.memos-elections-fr.subtitle": "Tracks major platforms behaviour over the French 2022 elections.",
```

2022-06-13 12:15 UTC, clementbiron commented
@MattiSG the current format of the illustration allow to show the content of a memo.

With fullwidth it gives a less good idea of the content and there is a an unsightly cut between the header and the intro of the memo. Thiis version makes me want to show only the black header. What do you think ?

![image](https://user-images.githubusercontent.com/364319/173350721-343e1902-c5b0-4cac-97e0-58246f29b151.png)

2022-06-13 14:24 UTC, MattiSG requested changes
Following our synchronous rebase and force-push, you should cherry-pick 416bfa3f6babe07a7087f5bd028f658d161831d5 to this branch.

2022-06-13 14:26 UTC, MattiSG commented
> This version makes me want to show only the black header. What do you think ?

I agree with the weird cut not looking good, but I would be more in favour of showing only the contents of the newsletter instead, as the black header looks too much like the main page layout.

2022-06-13 15:27 UTC, clementbiron commented
Good idea! 

I pushed my proposal. 
![image](https://user-images.githubusercontent.com/364319/173388122-13d5ca48-4837-4b9e-9db4-0176caf3772e.png)

2022-06-13 15:28 UTC, MattiSG commented
Great! I see the screenshot still has the current wording. Please make sure you include the changes for wording that had already been suggested 🙂

2022-06-13 15:45 UTC, MattiSG approved these changes
🚀

2022-06-13 15:49 UTC, merged