Add accessibility conformity mention
ambanum/OpenTermsArchive.org pull request #141
Opened 2022-06-15 12:52 UTC by clementbiron

2022-06-15 14:26 UTC, MattiSG requested changes
Please take a bit of time to double-check content before opening the PR 🙂 The triple email address should have been easy to spot 😉

2022-06-15 14:26 UTC, MattiSG commented on src/translations/en/accessibility.mdx
> +- E-mail: [contact@opentermsarchive.org](mailto:contact@opentermsarchive.orgcontact@opentermsarchive.orgcontact@opentermsarchive.org)
```suggestion
- E-mail: [contact@opentermsarchive.org](mailto:contact@opentermsarchive.org)
```

2022-06-15 14:26 UTC, MattiSG commented on src/translations/en/accessibility.mdx
> +- Contact [the representative of the Defender of Rights in your region](https://www.defenseurdesdroits.fr/saisir/delegues)
```suggestion
- Contact [the representative of the Défenseur des droits in your region](https://www.defenseurdesdroits.fr/saisir/delegues)
```

2022-06-15 14:26 UTC, MattiSG commented on src/translations/fr/accessibility.mdx
> +- Twitter : @openTerms
Same feedback as for the English version.

2022-06-15 17:44 UTC, MattiSG approved these changes
Tested locally 👍 Thanks @clementbiron 🙂

2022-06-15 17:44 UTC, MattiSG commented on src/translations/en/accessibility.mdx
> +- Send a letter by post (free of charge, do not put a stamp):
```suggestion
- Send a letter by post (free of charge in France, do not put a stamp):
```

2022-06-16 05:48 UTC, martinratinaud approved these changes

2022-06-16 06:21 UTC, martinratinaud commented
Also, I believe it would be great, if we want to ease the creation of pages, to have a "catch-all" route in `pages` (`[...slug].tsx`) that will:

- check if the corresponding `mdx` file exists
- if no -> return 404
- if yes -> display the content and use `frontMatter` to add SEO data directly within the mdx file

I believe this would end up with something similar than what github pages provide

Let me know if this is needed soon or if, considering the few pages we need right now, is overkill.

2022-06-16 12:55 UTC, clementbiron commented
@martinratinaud thanks Martin, let's talk about your suggestion's at the next planning.

2022-06-16 12:56 UTC, merged